
ALTER TABLE ShareDetails.Shares ADD CONSTRAINT
	PK_Shares PRIMARY KEY CLUSTERED 
	(
	ShareId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

